import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { getMessages } from "next-intl/server";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface props  {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}
export default async function RootLayout({children, params}:props) {
  const {locale} = await params;
  if(!hasLocale(routing.locales, locale)){
    notFound()
  }
const messages = await getMessages({locale});  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <NextIntlClientProvider locale={locale} messages={messages}>

        <Navbar/>
        {children}
        <Footer/>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
